### ISSUE TITLE
Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by johnRivs** [nuxt-community/router-module#8]
When I `nuxt` or `nuxt build`, I get this error: 
```
ERROR in ./node_modules/@nuxtjs/router/dist/index.js
Module not found: Error: Can't resolve 'fs' in 'MY_PROJECT\node_modules\@nuxtjs\router\dist'
 @ ./node_modules/@nuxtjs/router/dist/index.js 4:9-22
 @ multi vue vue-router vue-meta vuex @nuxtjs/router
Error: Webpack build exited with errors
    at MY_PROJECT\node_modules\nuxt\lib\builder\builder.js:498:27
    at emitRecords.err (MY_PROJECT\node_modules\webpack\lib\Compiler.js:269:13)
    at Compiler.emitRecords (MY_PROJECT\node_modules\webpack\lib\Compiler.js:375:38)
    at emitAssets.err (MY_PROJECT\node_modules\webpack\lib\Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (MY_PROJECT\node_modules\webpack\lib\Compiler.js:368:12)
    at next (MY_PROJECT\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (MY_PROJECT\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (MY_PROJECT\node_modules\tapable\lib\Tapable.js:222:13)
    at Compiler.afterEmit (MY_PROJECT\node_modules\webpack\lib\Compiler.js:365:9)
    at require.forEach.err (MY_PROJECT\node_modules\webpack\lib\Compiler.js:354:15)
    at MY_PROJECT\node_modules\async\dist\async.js:421:16
    at iteratorCallback (MY_PROJECT\node_modules\async\dist\async.js:998:13)
    at MY_PROJECT\node_modules\async\dist\async.js:906:16
    at MY_PROJECT\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nuxt@1.0.0 build: `nuxt build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nuxt@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\John\AppData\Roaming\npm-cache\_logs\2017-10-18T12_11_19_032Z-debug.log
```

**Comment by Atinux** [comment]
Hi @johnRivs 

Are you sure to use the last version of NPM and node >=7 ?

**Comment by YanLobat** [comment]
When you use `fs` in page templates, this error will be there

**Comment by johnRivs** [comment]
Mmm., not sure I follow. This package disables the pages directory so you can build the router yourself. I'm not even using `fs`.
